ARG RUBY_VERSION=3.3.5

FROM docker.io/library/ruby:${RUBY_VERSION}-slim AS dev 

# App lives here
WORKDIR /rails

# Install packages
RUN apt-get update -qq && \
apt-get install --no-install-recommends -y curl libvips sqlite3 build-essential git pkg-config && \
rm -rf /var/lib/apt/lists /var/cache/apt/archives

# set development environment 
ENV RAILS_ENV='development' \
BUNDLE_WITHOUT="" \
BUNDLE_PATH="/usr/local/bundle"

# Copy Gemfile and install all gems
COPY Gemfile Gemfile.lock ./
RUN bundle install 

COPY . .

EXPOSE 3000

CMD ["./bin/rails", "server", "-b", "0.0.0.0"]

